apiVersion: v1
kind: Service
metadata:
  name: vprodb      #name of the service
spec:
  selector:
    app: vprodb      # label name
  ports:
  - port: 3306
    targetPort: vprodb-port       # port name
    protocol: TCP
  type: ClusterIP