apiVersion: v1
kind: Service
metadata:
  name: vprocache01  # check application.propot
spec:
  selector:
    app: vpromc
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  type: ClusterIP